[
  { "brand": "CYRA.D", "generic": "Rabeprazole + Domperidone" },
  { "brand": "MOXIFORCE CV", "generic": "Amoxicillin + Clavulanate" },
  { "brand": "ODIMONT LC", "generic": "Montelukast + Levocetirizine" },
  { "brand": "OCECOUGH", "generic": "Ambroxol + Guaifenesin" },
  { "brand": "PACIMOL", "generic": "Paracetamol" },
  { "brand": "DOLO 650", "generic": "Paracetamol" },
  { "brand": "CROCIN", "generic": "Paracetamol" },
  { "brand": "CALPOL", "generic": "Paracetamol" },
  { "brand": "COMBIFLAM", "generic": "Ibuprofen + Paracetamol" },
  { "brand": "ZERODOL-SP", "generic": "Aceclofenac + Serratiopeptidase + Paracetamol" },
  { "brand": "MEFTAL-SPAS", "generic": "Mefenamic Acid + Dicyclomine" },
  { "brand": "ULTRACET", "generic": "Tramadol + Paracetamol" },
  { "brand": "FLEXON", "generic": "Ibuprofen + Paracetamol" },
  { "brand": "PAN 40", "generic": "Pantoprazole" },
  { "brand": "PANTOCID", "generic": "Pantoprazole" },
  { "brand": "PANTOCID DSR", "generic": "Pantoprazole + Domperidone" },
  { "brand": "OMEE", "generic": "Omeprazole" },
  { "brand": "ACILOC 150", "generic": "Ranitidine" },
  { "brand": "RANTAC", "generic": "Ranitidine" },
  { "brand": "DIGENE", "generic": "Magnesium Hydroxide + Simethicone" },
  { "brand": "GELUSIL", "generic": "Aluminium Hydroxide + Magnesium" },
  { "brand": "AUGMENTIN 625", "generic": "Amoxicillin + Clavulanic Acid" },
  { "brand": "CLAVAM 625", "generic": "Amoxicillin + Clavulanic Acid" },
  { "brand": "AZITHRAL", "generic": "Azithromycin" },
  { "brand": "ZIFI 200", "generic": "Cefixime" },
  { "brand": "TAXIM-O", "generic": "Cefixime" },
  { "brand": "MONOCEF", "generic": "Ceftriaxone" },
  { "brand": "METROGYL", "generic": "Metronidazole" },
  { "brand": "NORFLOX TZ", "generic": "Norfloxacin + Tinidazole" },
  { "brand": "OFLOX", "generic": "Ofloxacin" },
  { "brand": "SINAREST", "generic": "Paracetamol + Phenylephrine + Chlorpheniramine" },
  { "brand": "CHESTON COLD", "generic": "Cetirizine + Paracetamol + Phenylephrine" },
  { "brand": "ALLEGRA", "generic": "Fexofenadine" },
  { "brand": "LEVOCET", "generic": "Levocetirizine" },
  { "brand": "OKACET", "generic": "Cetirizine" },
  { "brand": "MONTEK LC", "generic": "Montelukast + Levocetirizine" },
  { "brand": "ASCORIL", "generic": "Terbutaline + Bromhexine + Guaifenesin" },
  { "brand": "BENADRYL", "generic": "Diphenhydramine" },
  { "brand": "GRILINCTUS", "generic": "Dextromethorphan + Chlorpheniramine" },
  { "brand": "GLYCOMET", "generic": "Metformin" },
  { "brand": "GLYCOMET GP", "generic": "Glimepiride + Metformin" },
  { "brand": "JALRA", "generic": "Vildagliptin" },
  { "brand": "TELMA", "generic": "Telmisartan" },
  { "brand": "TELMA H", "generic": "Telmisartan + Hydrochlorothiazide" },
  { "brand": "AMLOKIND", "generic": "Amlodipine" },
  { "brand": "ECOSPRIN", "generic": "Aspirin" },
  { "brand": "ATORVA", "generic": "Atorvastatin" },
  { "brand": "THYRONORM", "generic": "Thyroxine" },
  { "brand": "ZINCOVIT", "generic": "Multivitamin + Multimineral" },
  { "brand": "A TO Z", "generic": "Multivitamin" },
  { "brand": "SHELCAL 500", "generic": "Calcium + Vitamin D3" },
  { "brand": "UPRISE-D3", "generic": "Cholecalciferol (Vitamin D3)" },
  { "brand": "NEUROBION FORTE", "generic": "Vitamin B Complex" },
  { "brand": "EVION 400", "generic": "Vitamin E" },
  { "brand": "SUPRADYN", "generic": "Multivitamin + Minerals" },
  { "brand": "DEXORANGE", "generic": "Iron + Folic Acid + Vitamin B12" }
]