import type { PrescriptionResult } from '../src/types.js';

type MedicalDocument = { id: string; title: string; text: string; source: string; tags: string[] };
const knowledgeBase: MedicalDocument[] = [
  { id: 'emergency', title: 'Emergency care guidance', source: 'MedSutra safety policy', tags: ['emergency', 'symptoms', 'safety'], text: 'Seek urgent in-person care for chest pain, severe trouble breathing, seizures, fainting, signs of a severe allergic reaction, severe bleeding, or thoughts of self-harm. Do not use chat as emergency care.' },
  { id: 'prescription', title: 'Prescription safety', source: 'MedSutra safety policy', tags: ['prescription', 'dose', 'medicine'], text: 'Never start, stop, or change a prescription medicine from an AI response alone. Confirm unclear handwriting, unidentified medicines, allergies, interactions, and dosing changes with a clinician or pharmacist.' },
  { id: 'privacy', title: 'Privacy and support', source: 'MedSutra privacy policy', tags: ['privacy', 'data', 'support'], text: 'Medical information is only used to provide requested healthcare features. Do not share prescription images or medication details over an unverified support channel.' },
  { id: 'antibiotic', title: 'Antibiotic use', source: 'MedSutra clinical safety knowledge', tags: ['antibiotic', 'amoxicillin', 'azithromycin'], text: 'Antibiotics treat specific bacterial infections and should be taken exactly as prescribed. They do not treat viral colds or flu. Report signs of a serious allergy promptly.' },
  { id: 'pain', title: 'Pain medicine safety', source: 'MedSutra clinical safety knowledge', tags: ['pain', 'paracetamol', 'ibuprofen'], text: 'Combination products can contain the same pain medicine. Check ingredients before combining medicines, especially products containing paracetamol or NSAIDs.' },
];
function tokenize(value: string): string[] { return value.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter((word) => word.length > 2); }
function localRetrieve(query: string, limit = 4): MedicalDocument[] { const terms = new Set(tokenize(query)); return knowledgeBase.map((document) => ({ document, score: tokenize(`${document.title} ${document.tags.join(' ')} ${document.text}`).reduce((score, term) => score + (terms.has(term) ? 1 : 0), 0) })).filter(({ score }) => score > 0).sort((left, right) => right.score - left.score).slice(0, limit).map(({ document }) => document); }
async function createEmbedding(text: string): Promise<number[] | null> { const apiKey = process.env.GEMINI_API_KEY; if (!apiKey || !process.env.QDRANT_URL) return null; const model = process.env.GEMINI_EMBEDDING_MODEL || 'gemini-embedding-001'; const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:embedContent?key=${apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: `models/${model}`, content: { parts: [{ text }] } }) }); if (!response.ok) return null; const body = await response.json() as { embedding?: { values?: number[] } }; return body.embedding?.values || null; }
async function qdrantRetrieve(query: string, limit = 4): Promise<MedicalDocument[]> { const vector = await createEmbedding(query); const baseUrl = process.env.QDRANT_URL?.replace(/\/$/, ''); if (!vector || !baseUrl) return []; const headers: Record<string, string> = { 'Content-Type': 'application/json' }; if (process.env.QDRANT_API_KEY) headers['api-key'] = process.env.QDRANT_API_KEY; const response = await fetch(`${baseUrl}/collections/${encodeURIComponent(process.env.QDRANT_COLLECTION || 'medsutra_knowledge')}/points/query`, { method: 'POST', headers, body: JSON.stringify({ query: vector, limit, with_payload: true }) }); if (!response.ok) return []; const payload = await response.json() as { result?: { points?: Array<{ id: string; payload?: Record<string, unknown> }> } }; return (payload.result?.points || []).flatMap((point) => { const value = point.payload || {}; return typeof value.text === 'string' && typeof value.title === 'string' ? [{ id: String(point.id), title: value.title, text: value.text, source: typeof value.source === 'string' ? value.source : 'Configured knowledge base', tags: Array.isArray(value.tags) ? value.tags.filter((tag): tag is string => typeof tag === 'string') : [] }] : []; }); }
export async function retrieveKnowledge(query: string): Promise<MedicalDocument[]> { const external = await qdrantRetrieve(query); return external.length ? external : localRetrieve(query); }
async function memoryRequest(path: string, options: RequestInit): Promise<unknown> { const baseUrl = process.env.MEM0_BASE_URL?.replace(/\/$/, ''); const apiKey = process.env.MEM0_API_KEY; if (!baseUrl || !apiKey) return null; const response = await fetch(`${baseUrl}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Token ${apiKey}`, ...(options.headers || {}) } }); return response.ok ? response.json() : null; }
export async function getPatientMemory(userId?: string): Promise<string[]> { if (!userId) return []; const body = await memoryRequest(`/v1/memories?user_id=${encodeURIComponent(userId)}`, { method: 'GET' }) as { results?: Array<{ memory?: string }> } | null; return (body?.results || []).flatMap((entry) => typeof entry.memory === 'string' ? [entry.memory] : []).slice(0, 8); }
export async function savePatientMemory(userId: string, memory: string, consent: boolean): Promise<boolean> { if (!consent || !memory.trim()) return false; return Boolean(await memoryRequest('/v1/memories', { method: 'POST', body: JSON.stringify({ messages: [{ role: 'user', content: memory.slice(0, 4000) }], user_id: userId }) })); }
export async function generateGemini(contents: unknown[], systemInstruction?: string): Promise<string> { const apiKey = process.env.GEMINI_API_KEY; if (!apiKey) throw new Error('GEMINI_API_KEY is not configured on the server.'); const models = [process.env.GEMINI_MODEL || 'gemini-3.5-flash', 'gemini-2.5-flash', 'gemini-2.5-flash-lite']; for (const model of [...new Set(models)]) { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents, ...(systemInstruction ? { systemInstruction: { parts: [{ text: systemInstruction }] } } : {}) }) }); if (!response.ok) continue; const body = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> }; const text = body.candidates?.[0]?.content?.parts?.map((part) => part.text || '').join('').trim(); if (text) return text; } throw new Error('Gemini is temporarily unavailable.'); }
export async function answerMedicalQuestion(input: { question: string; history: Array<{ role: string; content: string }>; prescription?: PrescriptionResult; userId?: string; mode?: string }): Promise<{ answer: string; sources: string[]; grounded: boolean }> { const [documents, memory] = await Promise.all([retrieveKnowledge(input.question), getPatientMemory(input.userId)]); const context = documents.map((document) => `[${document.title} | ${document.source}]\n${document.text}`).join('\n\n'); const conversation = input.history.slice(-8).map((message) => `${message.role === 'user' ? 'Patient' : 'Assistant'}: ${message.content}`).join('\n'); const prompt = `Trusted knowledge:\n${context || 'No retrieved knowledge.'}\n\nPatient memory (only if relevant):\n${memory.join('\n') || 'None'}\n\nPrescription context:\n${JSON.stringify(input.prescription || {})}\n\nConversation:\n${conversation}\n\nQuestion: ${input.question}`; const system = `You are MedSutra's healthcare information assistant. Give concise, empathetic information in ${input.mode === 'clinical' ? 'clinical' : 'plain patient-friendly'} language. Prefer the supplied trusted knowledge and prescription context when relevant. If they don't cover the question, answer using your general medical knowledge, clearly noting when you're doing so, and always recommend confirming with a clinician or pharmacist for anything specific to the patient's situation. Never diagnose, prescribe, change doses, or present an emergency as chat-manageable.`; return { answer: await generateGemini([{ parts: [{ text: prompt }] }], system), sources: documents.map((document) => document.source), grounded: documents.length > 0 }; }
export async function draftCaregiverEmail(input: { profileName: string; prescription: PrescriptionResult; recipients?: string[] }): Promise<string> { const baseUrl = process.env.SLASHY_BASE_URL?.replace(/\/$/, ''); const apiKey = process.env.SLASHY_API_KEY; if (!baseUrl || !apiKey) throw new Error('Auto-Mail is not configured. Add SLASHY_API_KEY and SLASHY_BASE_URL on the server.'); const response = await fetch(`${baseUrl}/v1/workflows/prescription-email`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` }, body: JSON.stringify(input) }); if (!response.ok) throw new Error('The Auto-Mail service could not create a draft.'); const body = await response.json() as { draft?: string }; if (!body.draft) throw new Error('The Auto-Mail service did not return an email draft.'); return body.draft; }
export async function findPharmacyCoupons(input: { subtotal: number; medicineNames: string[] }): Promise<Array<{ code: string; savings: number; description: string }>> { const baseUrl = process.env.GENZDEAL_BASE_URL?.replace(/\/$/, ''); const apiKey = process.env.GENZDEAL_API_KEY; if (!baseUrl || !apiKey) throw new Error('Coupon recommendations are not configured.'); const response = await fetch(`${baseUrl}/v1/coupons/pharmacy`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` }, body: JSON.stringify(input) }); if (!response.ok) throw new Error('Coupon recommendations are temporarily unavailable.'); const body = await response.json() as { coupons?: Array<{ code?: string; savings?: number; description?: string }> }; return (body.coupons || []).flatMap((coupon) => typeof coupon.code === 'string' && typeof coupon.savings === 'number' ? [{ code: coupon.code, savings: coupon.savings, description: coupon.description || 'Pharmacy delivery offer' }] : []); }
export async function transcribeWithGnani(audioBase64: string, mimeType: string, language: string): Promise<string> { const baseUrl = process.env.GNANI_BASE_URL?.replace(/\/$/, ''); const apiKey = process.env.GNANI_API_KEY; if (!baseUrl || !apiKey) throw new Error('Voice transcription is not configured.'); const audio = Buffer.from(audioBase64, 'base64'); const form = new FormData(); form.append('audio_file', new Blob([audio], { type: mimeType || 'audio/webm' }), 'voice-recording.webm'); form.append('language_code', language); form.append('preferred_language', language); form.append('format', 'transcribe'); form.append('itn_native_numerals', 'true'); const response = await fetch(`${baseUrl}/stt/v3`, { method: 'POST', headers: { 'X-API-Key-ID': apiKey }, body: form }); if (!response.ok) throw new Error('Voice transcription is temporarily unavailable.'); const body = await response.json() as { transcript?: string }; if (!body.transcript) throw new Error('Voice transcription returned no text.'); return body.transcript; }
